### ISSUE TITLE
#9769 - Plugin needs to be updated to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [joshdoe/josm-conflation-plugin#11]
See https://josm.openstreetmap.de/ticket/9769

Is this plugin maintained?

**Comment by joshdoe** [comment]
Unfortunately I just don't have the time to maintain this plugin at the current time. I was hoping some other developer would start helping out, or there would be significant interest but it didn't materialize. So yes, currently this is unmaintained. However I'd be motivated enough to merge pull requests if that happens at some point.

**Comment by simon04** [comment]
This issue has been fixed in #7, but the jar file needs to be rebuilt.

**Comment by don-vip** [comment]
we're now using a fork: https://github.com/JOSM/josm-conflation-plugin
