### ISSUE TITLE
utilsplugin2 should be a requirement/auto-installed like JTS

### ISSUE THREAD

**Issue by oeon** [joshdoe/josm-conflation-plugin#2]
A user will get errors after installing this plugin unless utilsplugin2 is also installed. I _thought_ JTS gets automatically installed when installing the Conflation plugin - seems that utilsplugin2 should also OR at least documented.

**Comment by joshdoe** [comment]
Thanks for the report, it's in the code and will go in the next release. Until then at least it's documented here. :)
